config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :inventories
  resources :banner_items
  resources :likes
  resources :users
  resources :items
  resources :banners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main' ,to: 'users#main'
  post 'login' ,to: 'users#login'
  get 'banner/:id' ,to: 'users#banner'
  get 'search/:name' ,to: 'users#eachbanner'
  get 'inventory' ,to: 'users#inventory'
  get 'result/:name/:type/:id' ,to: 'users#result'
  get 'market' ,to: 'users#market'
  get 'buy/:inventory_id/:id' ,to: 'users#buy'
end

app/models/banner.rb
class Banner < ApplicationRecord
	has_many :likes
	has_many :banner_items
	def get_rate
		allItem = self.banner_items
		allName = Array.new 
		allItem.each do |itemID|
			item = Item.find_by(id: itemID.item_id)
			if allName.size == 0
				allName.push(item.itemname)
			elsif !(allName.include? item.itemname)
				allName.push(item.itemname)
			end
		end		
		return allName
	end

	def random_one(user_id)
		allItem = self.banner_items
		chooseItem = allItem.sample
		if chooseItem != nil
			item = Inventory.create(user_id: user_id, item_id: chooseItem.item_id,price: 0,status:"not for sell")
			item.save
			item = Item.find_by(id: chooseItem.item_id)
			chooseItem.destroy
			box = Array.new
			box.push(item.itemname)
			box.push(item.rarity)
			box.push(item.img_url)
			return box
		end
	end

	def five_random(user_id)
		allItem = self.banner_items
		chooseItems = allItem.sample(5)
		boxes = Array.new
		chooseItems.each do |chooseItem|
			item = Inventory.create(user_id: user_id, item_id: chooseItem.item_id,price: 0,status:"not for sell")
			item.save
			item = Item.find_by(id: chooseItem.item_id)
			chooseItem.destroy
			box = Array.new
			box.push(item.itemname)
			box.push(item.rarity)
			box.push(item.img_url)
			boxes.push(box)
		end
		return boxes
	end

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: %i[ show edit update destroy ]

  # GET /banners or /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1 or /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners or /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: "Banner was successfully created." }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1 or /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: "Banner was successfully updated." }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1 or /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: "Banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banner_params
      params.require(:banner).permit(:bannername ,:img_url,:content)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_with(model: banner) do |form| %>
  <% if banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
        <% banner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bannername %>
    <%= form.text_field :bannername %>
  </div>
  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banners</h1>

<table>
  <thead>
    <tr>
      <th>Bannername</th>
      <th>img_url</th>
      <th>content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.bannername %></td>
        <td><%= banner.img_url %></td>
        <td><%= banner.content %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bannername:</strong>
  <%= @banner.bannername %>
</p>

<p>
  <strong>img_url:</strong>
  <%= @banner.img_url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @banner.content %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>