config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :inventories
  resources :banner_items
  resources :likes
  resources :users
  resources :items
  resources :banners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main' ,to: 'users#main'
  post 'login' ,to: 'users#login'
  get 'banner/:id' ,to: 'users#banner'
  get 'search/:name' ,to: 'users#eachbanner'
  get 'inventory' ,to: 'users#inventory'
  get 'result/:name/:type/:id' ,to: 'users#result'
  get 'market' ,to: 'users#market'
  get 'buy/:inventory_id/:id' ,to: 'users#buy'
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :likes
	has_many :inventorys
	has_many :sellers, class_name: 'Transaction', foreign_key: 'seller_id'
	has_many :buyers,  class_name: 'Transaction', foreign_key: 'buyer_id'
	def get_banner
  		return listOfBanner = self.likes
	end

	def buyItem(inventory)
		time = Time.zone.now
		seller_id = inventory.user_id
		buyer_id = self.id
		item_id = inventory.item_id
		price = inventory.price
		self.credit -= Float(price)
		User.find_by(id: seller_id).credit += Float(price)
		tran = Transaction.create(dateTime: time, seller_id: seller_id, buyer_id: buyer_id, item_id: item_id, price: price)
		tran.save
		inventory.user_id = self.id
		inventory.status = "not for sale"
		inventory.save
		self.save
	end

	def buyGacha(price)
		self.credit -= price
		self.save
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy banner ]
  before_action :logged_in, except: %i[ index main login new create destroy update]
  before_action :is_user, only: %i[ show banner ]
  before_action :is_nuser, only: %i[ result buy ]

  @fLogin = false
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    temp = user_params["username"] 
    tempU = User.find_by(username:temp)
    if tempU != nil
      redirect_to main_path,alert: "Can't use this username"
    else
        respond_to do |format|
          if @user.save
            format.html { redirect_to main_path, notice: "User was successfully created." }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end  
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def main
    session[:user_id] = nil
    if @fLogin
      @user = User.find_by(username: @username)
    else
      @user = User.new
    end
  end

  def login
    luser = params[:user]
    @username = luser['username']
    @password = luser['password']
    @user = User.find_by(username: @username)
    respond_to do |format|
      if @user != nil 
        if @user.authenticate(@password.to_s)
          session[:user_id] = @user.id
          format.html { redirect_to "/banner/#{@user.id}", notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else 
          @fLogin = true
          format.html { redirect_to main_path, alert: "Wrong password"}
          format.json { render json: @user.errors, status: :unprocessable_entity}
        end
      else
        @fLogin = true
        @user = User.new
        format.html { redirect_to main_path ,alert: "Not found this user"}
        format.json { render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  def banner
    id = params[:id]
    @user = User.find_by(id: id)
    @banners = Banner.all
    # @banner = @user.get_banner
  end

  def eachbanner
    @user = User.find_by(id: session[:user_id])
  end

  def inventory
    @user = User.find_by(id: session[:user_id])
  end

  def market
    @user = User.find_by(id: session[:user_id])
  end

  def result
    @user = User.find_by(id: session[:user_id])
    banner = Banner.find_by(bannername: params[:name])
    if params[:type] == "one"
      @user.buyGacha(100)
      @boxes =  banner.random_one(session[:user_id])
    elsif params[:type] == "five"
      @user.buyGacha(400)
      @boxes =  banner.five_random(session[:user_id])
    end
  end

  def buy
    @inventory = Inventory.find_by(id: params[:inventory_id])
    @user = User.find_by(id: session[:user_id])
    if @inventory.status == "for sale" 
      @user.buyItem(@inventory)
    end
  end


  private
    def logged_in
      if(session[:user_id])
        return true
      else
        redirect_to main_path, alert: "Please login."
      end
    end

    def is_user
      if(session[:user_id] != @user.id)
        redirect_to main_path, alert: "Log in with wrong user"
      else
        return true
      end
    end

    def is_nuser
      if(session[:user_id].to_s != params[:id])
        redirect_to main_path, alert: "Log in with wrong user"
      else
        return true
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :credit)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.text_field :credit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_formMain.html.erb
<%= simple_form_for(@user, method: :post, url: '/login') do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Login"  %>
  </div>
  <a href= <%=new_user_path%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Sign up</a>
<% end %>

app/views/users/banner.html.erb
<p id="notice"><%= notice %></p>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <h3>Username: <%= @user.username %></h3>
</p>
<p>
  <h3>Credit:<%= @user.credit %></h3>
</p>

  <div>
    <%@banners = Banner.all%>
    <% @banners.each do |banner| %>
      
      <div class="card" style="width: 18rem;">
        <img src="https://cdn-wp.thesportsrush.com/2019/07/GettyImages-904853854.jpg" >
        <div class="card-body">
        <h5 class="card-title"><%=banner.bannername%></h5>
        <p class="card-text"><%=banner.content%></p>
        <a href="/search/<%=banner.bannername%>" class="btn btn-primary">Gacha!</a>
        </div>
      </div>
    <% end %>
  </div>

<!-- <div class="modal fade" id="likeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Total Likes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id = "body">
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(".xyz").click(function(){
      var myModal = new bootstrap.Modal(document.getElementById('likeModal'), {})
      $(".modal-body").empty();
      const data = $(this).data("like");
      //$(".modal-body").text(data);
      for (let i = 0 ; i < data.length; i++) {
        $(".modal-body").append(`<a href="/profile/${data[i]}">${data[i]}</a><br>`);
      }
      myModal.show();
  })
</script> -->

app/views/users/buy.html.erb
<p id="notice"><%= notice %></p>
<%@user = User.find_by(id: session[:user_id])%>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<%@inventory = Inventory.find_by(id: params[:inventory_id])%>
<%item = Item.find_by(id: @inventory.item_id) %>

<img src="<%=item.img_url%>"    alt="...">
<p><%=item.itemname%></p>
<p>
  <strong>From Username:</strong>
  <%= User.find_by(id: @inventory.user_id).username %>
</p>

<p>
  <strong>To Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>


<a href="/inventory" class="btn btn-primary">Back</a>

app/views/users/eachbanner.html.erb
<p id="notice"><%= notice %></p>

<%name = params[:name]%>
<%banner = Banner.find_by(bannername: name)%>
<%allItem = banner.get_rate%>
<%allRate = Array.new%>
<% allItem.each do |itemName| %>
  <%item = Item.find_by(itemname: itemName)%>
  <%itemDetail = Array.new%>
  <%itemDetail.push(itemName)%>
  <%itemDetail.push(item.rarity )%>
  <%allRate.push(itemDetail)%>
<% end %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <h3>Username: <%= @user.username %></h3>
</p>
<p>
  <h3>Credit:<%= @user.credit %></h3>
</p>


<p>
  <strong><%= banner.bannername %></strong>
</p>
<img src="<%= banner.img_url%>" alt="...">
<p><%=banner.content%></p>

<button class="card-link rate" data-bs-toggle="modal" data-bs-target="#rateModal1" data-like = '<%=allRate%>' >
Rate
</button>
<%@user = User.find_by(id: session[:user_id])%>
<%if banner.banner_items.size >= 1 and @user.credit >=100%>
<a href="/result/<%=name%>/one/<%=@user.id%>" class="btn btn-primary">Get X1 $100</a>
<%end%>
<%if banner.banner_items.size >= 5 and @user.credit >=400%>
<a href="/result/<%=name%>/five/<%=@user.id%>" class="btn btn-primary">Get X5 $400</a>
<%end%>







<div class="modal fade" id="rateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Item Rate</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body-rate" id = "body">
        <table>
          <thead>
            <tr>
              <th colspan="1"></th>
              <th>name</th>
              <th>rarity</th>
            </tr>
          </thead>

          <tbody class= "body-rate">
          </tbody>
        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- <div class="modal fade" id="randomOneModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Item that you Got</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body-one" id = "body">
        
        
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> -->



<script>
  // $(".getOne").click(function(){
  //   var myModal = new bootstrap.Modal(document.getElementById('randomOneModal'), {})
  //   $(".modal-body-one").empty();
  //   const data = $(this).data("like");
  //     $(".modal-body-one").append(`<p>${data[0]}</p><img src="${data[2]}" class="card-img-top" alt="..."><p>${data[1]}</p>`);
  //   myModal.show();
  // })

  // $(".getFive").click(function(){
  //   var myModal = new bootstrap.Modal(document.getElementById('randomFiveModal'), {})
  //   $(".modal-body-five").empty();
  //   const data = $(this).data("like2");
  //   for (let i = 0 ; i < data.length; i++) {
  //     $(".modal-body-five").append(`<p>${data[i][0]}</p><img src="${data[i][2]}" class="card-img-top" alt="..."><p>${data[i][1]}</p>`);
  //     $(".modal-body-five").append(`<p>------------------------------------------</p>`);
  //   }
  //   myModal.show();
  // })


  $(".rate").click(function(){
    var myModal = new bootstrap.Modal(document.getElementById('rateModal'), {})
    $(".body-rate").empty();
    const data = $(this).data("like");
    for (let i = 0 ; i < data.length; i++) {
      $(".body-rate").append(`<tr><td style="background-image: url('${data[i][2]} ')" width="100%"><td>${data[i][0]}</td>
        <td>${data[i][1]}</td>
      </tr>`);
      }
    myModal.show();
  })  
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th>Credit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.credit %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/inventory.html.erb
<p id="notice"><%= notice %></p>
<%@user = User.find_by(id: session[:user_id])%>
<%items = @user.inventorys%>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <h3>Username: <%= @user.username %></h3>
</p>
<p>
  <h3>Credit:<%= @user.credit %></h3>
</p>


<p id="notice"><%= notice %></p>

<h1>Your Item</h1>

    <div class="box">
      <% items.each do |itemID| %>
      <%item = Item.find_by(id:itemID.item_id)%>
      <div class="card item" style="width: 18rem; ">
      <img class="card-img-top" src="<%=item.img_url%>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= item.itemname%></h5>
        <p class="card-text"><%= item.rarity %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= itemID.status %></li>
      </ul>
      <div class="card-body">
        <a href="<%=edit_inventory_path(itemID)%>" class="card-link">set status</a>
      </div>
    </div>
    </div>
    
      
    <% end %>

<style type="text/css">

</style>

app/views/users/main.html.erb
<h1>Main</h1>

<%= render 'formMain', user: @user %>

app/views/users/market.html.erb
<%@user = User.find_by(id: session[:user_id])%>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <h3>Username: <%= @user.username %></h3>
</p>
<p>
  <h3>Credit:<%= @user.credit %></h3>
</p>


<p id="notice"><%= notice %></p>

<h1>Users</h1>


  <%items =Inventory.where(status:"for sale")%>
  
    <% items.each do |itemID| %>
      <%item = Item.find_by(id:itemID.item_id)%>
      <div class="card item" style="width: 18rem; ">
      <img class="card-img-top" src="<%=item.img_url%>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= item.itemname%></h5>
        <p class="card-text"><%= item.rarity %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= itemID.status %></li>
        <li class="list-group-item"><%= itemID.price %></li>
      </ul>
      <div class="card-body">
        <%if itemID.user_id != @user.id and @user.credit >= itemID.price %>
         <a href="/buy/<%=itemID.id%>/<%=@user.id%>" class="card-link">Buy</a>
        <%end%>
      </div>
      <%end%>
    

<a href="/inventory" class="btn btn-primary">Back</a>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/result.html.erb
<p id="notice"><%= notice %></p>
<%@user = User.find_by(id: session[:user_id])%>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GAsha FiFA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/banner/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/inventory">Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "/market">Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @user.credit %>
</p>

<%if params[:type] == "one"%>
  <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%=@boxes[2]%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%=@boxes[0]%></h5>
    <p class="card-text"><%=@boxes[1]%></p>
  </div>
</div>
  <!-- <p><%=@boxes[0]%></p>
  <img src="<%=@boxes[2]%>"  alt="..." width="500" height="600">
  <p><%=@boxes[1]%>/p>
  <p>------------------------------------------</p> -->
<%else%>
<%@boxes.each do |item|%>
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="<%=item[2]%>" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%=item[0]%></h5>
      <p class="card-text"><%=item[1]%></p>
    </div>
  </div>
  <!-- <p><%=item[0]%></p>
  <img src="<%=item[2]%>"  alt="...">
  <p><%=item[1]%>/p>
  <p>------------------------------------------</p> -->
<%end%>
<%end%>

<a href="/inventory" class="btn btn-primary">Back</a>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @user.credit %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>